version: "3"

services:

  burpsuite:
    container_name: htb-burpsuite
    build:
      context: ../../docker/burpsuite
    ports:
      - 5900:5900
      - 6080:6080
      # proxy
      - 8080:8081
    hostname: burpsuite
    devices:
      - /dev/net/tun
    volumes:
      - ./share/:/share

  lab:
    container_name: htb-lab
    build:
      context: ../../docker/lab
    ports:
      # vnc
      - 5901:5900
      # novnc
      - 6081:6080
    hostname: lab
    # required by openvpn
    devices:
      - /dev/net/tun
    volumes:
      - ./share/:/share
      - wordlists:/usr/share/wordlists
  
  metasploit:
    container_name: htb-metasploit
    build:
      context: ../../docker/metasploit
    # equivalent to "docker run -i"
    stdin_open: true
    # equivalent to "docker run -t"
    tty: true
    ports:
      - 4444:4444
    hostname: metasploit
    devices:
      - /dev/net/tun
    volumes:
      - ./share/:/share
 
  wordlists:
    container_name: htb-wordlists
    build:
      context: ../../docker/wordlists
    stdin_open: true
    tty: true
    hostname: wordlists
    volumes:
      - wordlists:/usr/share/wordlists

volumes:
  wordlists:
