version: "3"

services:

  burpsuite:
    container_name: htb-burpsuite
    build:
      context: ../../docker/burpsuite
      args:
        - BURP_VERSION=2021.2
        - BURP_CHECKSUM=2c4c67ce7c0252d75faf8b43887562c67578a4cb02952f10876ac79e9e966933
    ports:
      - 127.0.0.1:5900:5900
      - 127.0.0.1:6080:6080
      # proxy
      - 127.0.0.1:8080:8081
    hostname: burpsuite
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./share/:/share

  lab:
    container_name: htb-lab
    build:
      context: ../../docker/lab
    # restrict access to localhost
    # https://github.com/docker/for-linux/issues/690
    ports:
      # vnc
      - 127.0.0.1:5901:5900
      # novnc
      - 127.0.0.1:6081:6080
    hostname: lab
    cap_add:
      # required by openvpn and wireshark
      - NET_ADMIN
    devices:
      # required by openvpn
      - /dev/net/tun
    sysctls:
      # required by openvpn: disable ipv6
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./share/:/share
      - wordlists:/usr/share/wordlists
  
  metasploit:
    container_name: htb-metasploit
    build:
      context: ../../docker/metasploit
    # equivalent to "docker run -i"
    stdin_open: true
    # equivalent to "docker run -t"
    tty: true
    ports:
      - 127.0.0.1:4444:4444
    hostname: metasploit
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ./share/:/share
 
  wordlists:
    container_name: htb-wordlists
    build:
      context: ../../docker/wordlists
    stdin_open: true
    tty: true
    hostname: wordlists
    volumes:
      - wordlists:/usr/share/wordlists

volumes:
  wordlists:
