yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules

# acorn issue preventing pnp
# https://github.com/terser/html-minifier-terser/issues/73
# https://github.com/terser/terser/issues/1076
# https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md
# https://github.com/yarnpkg/berry/issues/587
# https://github.com/yarnpkg/yarn/issues/7098
#nodeLinker: pnp
#pnpMode: "loose"
#pnpFallbackMode: "all"
