name: Docker CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-*.yml'
      - 'docker/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/wordlists
          # if false it will only build
          push: false
          # TODO wordlists
          tags: ${{ steps.meta.outputs.tags }}
