name: Docker CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-*.yml'
      - 'docker/**'

env:
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  docker-wordlists:
    name: Docker
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY_NAME }}/wordlists
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./docker/wordlists
          # if false it will only build
          push: true
          # TODO wordlists
          tags: ${{ steps.meta.outputs.tags }}
