name: Website CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/website-*.yml'
      - 'website/**'
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './website/.nvmrc'
      - name: Yarn build
        working-directory: ./website
        run: |
          yarn install --frozen-lockfile
          yarn build
