name: Website CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/website-*.yml'
      - 'website/**'
      - 'docs/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        working-directory: ./website
        with:
          node-version-file: '.nvmrc'
          cache: yarn
      - name: Yarn build
        run: |
          yarn install --frozen-lockfile
          yarn build
