name: Deploy website to GitHub Pages

on:
  push:
    tags: ['v*']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
          node-version: '16'
      - name: Build website
        working-directory: website
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
